version: '2'
services:

  front-envoy:
    build:
      context: ./
      dockerfile: Dockerfile-front
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  donutsalon-1:
    build:
      context: ./
      dockerfile: Dockerfile-back
    networks:
      envoymesh:
        aliases:
          - donutsalon-1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"
      - "8080"
    ports:
      - "9001:80"
      - "8081:8080"

networks:
  envoymesh: {}