FROM rnburn/envoy-jaeger:0.11

RUN apt-get update && \
    apt-get install -qqy \
  gettext \
	ca-certificates
COPY jaeger.yaml /etc/jaeger.yaml
COPY envoy-front.json /etc/envoy.json
COPY ls_access_token /etc/ls_access_token
COPY start_front.sh /usr/local/bin/start_front.sh
RUN ln -s /usr/local/lib/libjaegertracingd.so /usr/local/lib/libjaegertracing.so
EXPOSE 80
EXPOSE 8001
ENTRYPOINT /usr/local/bin/start_front.sh
