version: '2'
services:

  front-envoy:
    build:
      context: ./
      dockerfile: Dockerfile-front
    networks:
      envoymesh:
        aliases:
          - front-envoy
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  donutsalon-1:
    build:
      context: ./
      dockerfile: Dockerfile-back
    networks:
      envoymesh:
        aliases:
          - donutsalon-1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"
      - "8080"
    ports:
      - "9001:80"
      - "8081:8080"

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      envoymesh:
        aliases:
          - jaeger
    expose:
      - "9411"
      - "16686"
      - "5775"
      - "6831"
      - "6832"
      - "5778"
      - "14268"

    ports:
      - "9411:9411"
      - "16687:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14268:14268"

networks:
  envoymesh: {}
