version: '2'
services:

  front-envoy:
    build:
      context: ./
      dockerfile: Dockerfile-front
    networks:
      envoymesh:
        aliases:
          - front-envoy
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  donutsalon-2:
    build:
      context: ./
      dockerfile: Dockerfile-back
    networks:
      envoymesh:
        aliases:
          - donutsalon-2
    environment:
      - SERVICE_NAME=2
    expose:
      - "80"
      - "8080"
    ports:
      - "9001:80"
      - "8081:8080"

  jaeger:
    image: jaegertracing/all-in-one
    networks:
      envoymesh:
        aliases:
          - jaeger
    expose:
      - "9411"
      - "16686"
    ports:
      - "9411:9411"
      - "16686:16686"

networks:
  envoymesh: {}
